# Copy and paste everything below (not including) the --- into the
# "controllers" section of your reactor.yaml file.
---

  - id: opensprinkler
    name: OpenSprinkler
    implementation: OpenSprinklerController
    enabled: true
    config:
      #
      # Replace the IP with that of your OpenSprinkler host below.
      host: 192.168.1.41

      # default hash for opendoor
      password: a6d82bced638de3def1e9bbb4983225c

      # topic as configured in options
      topic: os/ABCD

      # MSR MQTT Controller ID for MQTT integration
      #mqtt_controller: mqtt

      # interval for refresh: default 5 secs
      #interval: 5000

      # timeout: default 15 secs
      #timeout: 15000

      # error_interval: default 10 secs
      #error_interval: 10000

      # default_zone_duration: default 60 secs
      #default_zone_duration: 60

      # default_raindelay_duration: default 1 hour
      #default_raindelay_duration: 1